Addressing SQLAlchemy python import issues due to version skew...
The attempt here is to address the module import failures that have
been happening, especially in situations where the install is being
done on nodes with a newer version of SQLAlchemy.

(May have to roll back if this fix is not "deep" enough)

In initial tests these seem to work...

Issue as reported:

I come back on this blocking issue. It appears when installing 1.6.0:

Traceback (most recent call last):
  File "/usr/local/uvcdat/bin/esgf_node_manager_initialize", line 5, in <module>
    pkg_resources.run_script('esgf-node-manager==0.1.5', 'esgf_node_manager_initialize')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 489, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1207, in run_script
  File "/usr/local/uvcdat/lib/python2.7/site-packages/esgf_node_manager-0.1.5-py2.7.egg/EGG-INFO/scripts/esgf_node_manager_initialize", line 10, in <module>
    from migrate.versioning.exceptions import DatabaseAlreadyControlledError
ImportError: No module named exceptions
ERROR: Could not create esgf _____  database tables in esgcet